interface Analysis {
  id: string;
  filename: string;
  transcription: string;
  risk_score: number;
  status: "safe" | "suspicious" | "danger";
  ai_summary: string;
  is_ai_generated: boolean;
  confidence_score: number;
  created_at: string;
  threats: Array<{
    id: string;
    threat_type: string;
    description: string;
    severity: "low" | "medium" | "high";
    confidence: number;
    recommendation: string;
  }>;
}

export function exportToJson(analysis: Analysis) {
  const data = JSON.stringify(analysis, null, 2);
  const blob = new Blob([data], { type: "application/json" });
  downloadBlob(blob, `echo-audit-report-${analysis.id.slice(0, 8)}.json`);
}

export function exportToPdf(analysis: Analysis) {
  // Create a printable HTML report
  const threatsList = analysis.threats
    .map(t => `
      <div style="margin: 10px 0; padding: 10px; border-left: 3px solid ${
        t.severity === 'high' ? '#ef4444' : t.severity === 'medium' ? '#f59e0b' : '#eab308'
      }; background: #f8fafc;">
        <strong>${t.threat_type}</strong> (${t.severity.toUpperCase()})
        <p style="margin: 5px 0; font-size: 14px;">${t.description}</p>
        <p style="margin: 5px 0; font-size: 12px; color: #64748b;"><em>Recommendation: ${t.recommendation}</em></p>
      </div>
    `)
    .join('');

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Echo-Audit Report - ${analysis.filename}</title>
      <style>
        body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1e293b; }
        h1 { color: #0f172a; border-bottom: 2px solid #06b6d4; padding-bottom: 10px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; }
        .risk-score { font-size: 48px; font-weight: bold; color: ${
          analysis.status === 'danger' ? '#ef4444' : analysis.status === 'suspicious' ? '#f59e0b' : '#22c55e'
        }; }
        .status { text-transform: uppercase; font-weight: bold; color: ${
          analysis.status === 'danger' ? '#ef4444' : analysis.status === 'suspicious' ? '#f59e0b' : '#22c55e'
        }; }
        .meta { color: #64748b; font-size: 14px; }
        .section { margin: 20px 0; }
        .section-title { font-size: 16px; font-weight: 600; color: #475569; margin-bottom: 10px; }
        .summary { background: #f1f5f9; padding: 15px; border-radius: 8px; }
        .transcription { background: #f8fafc; padding: 15px; border-radius: 8px; font-family: monospace; font-size: 13px; white-space: pre-wrap; max-height: 300px; overflow-y: auto; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; text-align: center; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>🛡️ Echo-Audit Threat Report</h1>
      
      <div class="header">
        <div>
          <p class="meta"><strong>File:</strong> ${analysis.filename}</p>
          <p class="meta"><strong>Date:</strong> ${new Date(analysis.created_at).toLocaleString()}</p>
          <p class="meta"><strong>Report ID:</strong> ${analysis.id}</p>
        </div>
        <div style="text-align: right;">
          <div class="risk-score">${analysis.risk_score}</div>
          <div class="status">${analysis.status}</div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">AI Analysis Summary</div>
        <div class="summary">
          ${analysis.ai_summary}
          <p style="margin-top: 10px; font-size: 13px;">
            <strong>AI Voice Detected:</strong> ${analysis.is_ai_generated ? 'Yes ⚠️' : 'No ✓'}
            &nbsp;|&nbsp;
            <strong>Confidence:</strong> ${Math.round((analysis.confidence_score || 0) * 100)}%
          </p>
        </div>
      </div>

      ${analysis.threats.length > 0 ? `
        <div class="section">
          <div class="section-title">Detected Threats (${analysis.threats.length})</div>
          ${threatsList}
        </div>
      ` : '<p>No threats detected.</p>'}

      <div class="section">
        <div class="section-title">Full Transcription</div>
        <div class="transcription">${analysis.transcription}</div>
      </div>

      <div class="footer">
        Generated by Echo-Audit • AI Voice Analysis System • ${new Date().toISOString()}
      </div>
    </body>
    </html>
  `;

  // Open in new window for printing
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  }
}

export function exportToCsv(analyses: Analysis[]) {
  const headers = ['ID', 'Filename', 'Date', 'Risk Score', 'Status', 'AI Generated', 'Threats Count', 'Summary'];
  const rows = analyses.map(a => [
    a.id,
    a.filename,
    new Date(a.created_at).toISOString(),
    a.risk_score.toString(),
    a.status,
    a.is_ai_generated ? 'Yes' : 'No',
    a.threats?.length?.toString() || '0',
    `"${(a.ai_summary || '').replace(/"/g, '""')}"`,
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `echo-audit-export-${Date.now()}.csv`);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
